# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            # routes starting with /api - response will be serialized into json
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            # all other routes - response will be formatted with twig, as it was before
            - { path: ^/, prefer_extension: true, fallback_format: html,  priorities: [ html, '*/*'] }
