controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: ''
        vi: '/vi'

api_controllers:
    resource: ../../src/Controller/API/
    type: annotation
    prefix: /api/v1/
